import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Layout from '../components/layout';
const Home: NextPage = () => {
  return (
    <Layout className={styles.container}>
      <Head>
        <title>광고없는 사이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
};

export default Home;
